export const data = [
  { id: 1, value: 1, type: "number" },
  { id: 2, value: 2, type: "number" },
  { id: 3, value: 3, type: "number" },
  { id: 4, value: 4, type: "number" },
  { id: 5, value: 5, type: "number" },
  { id: 6, value: 6, type: "number" },
  { id: 7, value: 7, type: "number" },
  { id: 8, value: 8, type: "number" },
  { id: 9, value: 9, type: "number" },
  { id: 10, value: 0, type: "number" },
  { id: 11, value: "+", type: "operator" },
  { id: 12, value: "-", type: "operator" },
  { id: 13, value: "=", type: "operator" },
  { id: 14, value: "*", type: "operator" },
  { id: 15, value: "/", type: "operator" },
  { id: 16, value: "C", type: "Reset" },
];
